### ISSUE TITLE
Surface missing oc-id service configuration in webui

### ISSUE THREAD

**Issue by jtimberman** [chef/chef-analytics#11]
When a user has forgotten to set up oc-id for Analytics, the Analytics webui will redirect to an empty page. We should present them with a more informative error message like "Couldn't find the oc-id authentication service, did you configure it in Chef Analytics?"

The preflight-check subcommand for opscode-analytics-ctl is aware of this misconfiguration and will display appropriate output.

```
$ sudo opscode-analytics-ctl preflight-check

[ERROR] No oc-id identity service supplied in actions-source.json
 [ERROR] oc-id uid or secret not provided
[FAILURE] Preflight check failed. Please check the installation instructions at http://docs.opscode.com/install_analytics.html
```

**Comment by metadave** [comment]
https://chef.leankit.com/Boards/View/87391175/166465720

**Comment by abuecker** [comment]
On leankit board.
