### ISSUE TITLE
Show only changed lines in the diff view

### ISSUE THREAD

**Issue by glasschef** [chef/chef-analytics#12]
In Analytics, please only show the changed lines in the diff view (like GitHub/GitLab does for code). There’s so much data in node attributes it’s a ton of scrolling otherwise.

(request from customer)

**Comment by dblessing** [comment]
:+1: Thanks for opening this, @glasschef

**Comment by echohack** [comment]
+1 on this. Parsing through nearly 9000 lines of text to find the two changed lines in the diff view is not good. :(

**Comment by juliandunn** [comment]
I moved this ticket to our internal JIRA as an enhancement. Thank you all for the suggestion.
