### ISSUE TITLE
Upgrade embedded Java to Java 8

### ISSUE THREAD

**Issue by tfitch** [chef/chef-analytics#14]
End of Public Updates for Java 1.7 is coming in April 2015. http://www.oracle.com/technetwork/java/eol-135779.html

We need the Java embedded in Chef Analytics to be updated to a Java 8 (1.8).

Currently it is `/opt/opscode-analytics/embedded/jre - java version "1.7.0_25"`

Thanks!

**Comment by jamesc** [comment]
Right now, we're blocked on this by storm not publicly supporting 1.8.  To be investigated if it can run.

**Comment by kmacgugan** [comment]
https://github.com/chef/omnibus-analytics/pull/216

**Comment by metadave** [comment]
analytics_test passes against @kmacgugan's PR above.

**Comment by sersut** [comment]
I think we will need to update a security setting for integration service to be compatible with Java 8. We will update it out of band from this PR. We will need to test integration service with Kyleen's PR and see if we have an issue. /cc: @mcquin

**Comment by sersut** [comment]
Closing this. We will fix any issue that we discover for the integration service.
