### ISSUE TITLE
Upgrade rabbitmq

### ISSUE THREAD

**Issue by jeremiahsnapp** [chef/chef-analytics#15]
Analytics is shipping with a very old rabbitmq 2.7.1 while Chef Server 12 is shipping with 3.3.4. Can Analytics ship with 3.3.4 too?

**Comment by sersut** [comment]
@jeremiahsnapp is there a specific reason to do the upgrade NOW!!! :smile:

**Comment by jeremiahsnapp** [comment]
I'm sure there are lots of good reasons that I'm not aware of. :)

Actually I was doing a lot digging around with rabbit related stuff on the Chef Server and I thought I'd take a quick look at rabbit on Analytics. I was surprised to find the `rabbitmqctl` syntax I was using failed on Analytics which of course led me to the realization that rabbit on Analytics is very old.

Anecdotally speaking, some of the research I was doing leads me to believe it's very likely that there are good reasons to upgrade but I'm not an expert in these matters and I can't rattle them off the top of my head right now.

If it's difficult to upgrade soon then maybe just put this somewhere on the board to get to in the not too distant future?

**Comment by sersut** [comment]
Exactly... I was just asking to see if there was an immediate need for it :smile:

**Comment by jamesc** [comment]
Doh !  I was sure I updated that at the same point as I upgraded Chef Server!

It's pretty easy to upgrade - a small difference in a startup script, but not too hard.

**Comment by juliandunn** [comment]
I think we would probably do this as part of the RabbitMQ externalization project, or when a customer requirement needs it.
