### ISSUE TITLE
Allow Analytics System to Run Under HTTP

### ISSUE THREAD

**Issue by sean-horn** [chef/chef-analytics#16]
As a customer, I would like to run Analytics purely under http, with a hardware load balancer terminating the SSL connections.

Currently, it appears the Analytics Standalone nginx config only supports redirecting 80->443 https://github.com/chef/omnibus-analytics/blob/master/files/cookbooks/opscode-analytics/templates/default/nginx/nginx.conf.erb#L37

**Comment by juliandunn** [comment]
@sean-horn We have decided not to work on this issue for now. Can you follow up with me privately about what customer and what ticket #.
