### ISSUE TITLE
SMTP Notifications require username and password

### ISSUE THREAD

**Issue by NickFitz** [chef/chef-analytics#17]
It is not possible to configure SMTP Notifications to use an SMTP server which does not use SMTP AUTH, such as one which uses client IP address for authentication and authorisation.

When configuring an SMTP notification, the configuration form includes required fields for username and password. However, not all mail servers use the SMTP AUTH extensions to SMTP that require such fields. 

In such a case, even if one supplies meaningless values for username and password, no notifications are sent. I suspect, though this is merely conjecture, that upon connecting to the SMTP server, the client fails to take account of the fact that no SMTP AUTH requirement is advertised in the EHLO response and attempts to proceed with authentication, causing the server to drop the connection; or alternatively that, having received no advertisement of a required SMTP AUTH method, the client itself abandons the attempt to establish a session.

We have confirmed that the Chef Analytics server on which my client is experiencing this problem is able to send mail through the configured SMTP server manually, that is, when a connection to the SMTP server is established from a shell on the Chef Analytics server and the SMTP commands to send a new message are entered directly from the keyboard.

**Comment by metadave** [comment]
Thanks for the bug report @NickFitz, we'll take a look.

cc @chef/analytics-data-integrations

**Comment by sersut** [comment]
Thanks for reporting this @NickFitz.

**Comment by NickFitz** [comment]
The most recent version of Analytics fixes this issue. Thanks :-)
