### ISSUE TITLE
Path for jna-storm tmp objects should be configurable 

### ISSUE THREAD

**Issue by glasschef** [chef/chef-analytics#19]
On some systems, the /tmp/ directory is marked `noexec`, which causes issues when storm tries to use files like `/tmp/jna-storm/jna502856451395738988.tmp`.  If we were able to specify a different directory, we could work around these kinds of restrictions.

```
java.lang.UnsatisfiedLinkError: /tmp/jna-storm/jna502856451395738988.tmp: /tmp/jna-storm/jna502856451395738988.tmp: failed to map segment from shared object: Operation not permitted
	at java.lang.ClassLoader$NativeLibrary.load(Native Method) ~[na:1.7.0_25]
	at java.lang.ClassLoader.loadLibrary1(ClassLoader.java:1957) ~[na:1.7.0_25]
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1882) ~[na:1.7.0_25]
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1843) ~[na:1.7.0_25]
```

https://getchef.zendesk.com/agent/tickets/3428

**Comment by sean-horn** [comment]
Maybe turn this into a Preflight check for “noexec” on /tmp for everyone else. If it's on, fail pointing out the issue

**Comment by metadave** [comment]
+1 @sean-horn, I like it

**Comment by lrosenberg-hotwire** [comment]
As the customer who found/reported the bug -- this approach will NOT work. /tmp is set noexec on purpose for security reasons and our information security team would really like it to stay that way. We were allowed to make a temporary exception in this case until you were able to properly fix it by enabling an alternate location for the files that are being executed.

**Comment by metadave** [comment]
I think the solution is to:

- a) have a preflight check that fails if the Storm temp directory is noexec
- b) have a way to configure Storms temp dir if the preflight check fails.

**Comment by juliandunn** [comment]
This issue is being worked on - we have moved it to our internal Leankit as AN-166
