### ISSUE TITLE
When configuring Notifications, it would be nice to be able to quickly test settings

### ISSUE THREAD

**Issue by glasschef** [chef/chef-analytics#22]
A customer was having some difficulty figuring out the right way to set up his SMTP Notification rules, and expressed a desire to have a button on that page to quickly test out a Notification to see if his configuration would produce the desired results (a successful notification).

**Comment by sersut** [comment]
A very nice to have feature. Thanks for filing this @glasschef

**Comment by echohack** [comment]
+1 Setting up the email client (like postfix) and getting it hooked into notifications is the hardest part of setting up Chef Analytics. A "test" button that returns good errors would be AWESOME.

**Comment by juliandunn** [comment]
Thanks @glasschef ... I put this in our jira backlog. If you get a chance can you DM me the customer's Zendesk ticket
