### ISSUE TITLE
Reporting 1.3.0:  ffi-yajl Issue With Embedded chef-client 11.12.2

### ISSUE THREAD

**Issue by sean-horn** [chef/chef-analytics#23]
As a customer of Reporting, I would like to see clean runs of `opscode-reporting-ctl reconfigure`.

Normally, this could be ignored, but when trying to drive a reporting install with a cookbook, this STDERR output from the embedded chef-client gets in the way

    [root@centos-6 bin]# opscode-reporting-ctl reconfigure
    the ffi-yajl and yajl-ruby gems have incompatible C libyajl libs and should not be loaded in the same Ruby VM
    falling back to ffi which might work (or might not, no promises)

An equivalent update in the Chef Server 12.0.7 embedded chef-client was done here: https://github.com/chef/opscode-omnibus/pull/664

**Comment by schisamo** [comment]
Somewhat related issue in delivery-cluster: https://github.com/opscode-cookbooks/delivery-cluster/issues/79

**Comment by sean-horn** [comment]
Closing in favor of Analytics Leankit card https://chef.leankit.com/Boards/View/115871040/194417066
