### ISSUE TITLE
Need more granular settings in opscode-analytics.rb

### ISSUE THREAD

**Issue by vinyar** [chef/chef-analytics#24]
Presently, there is no way to way overwrite postgresql settings via opscode-analytics.rb

For example: postgresql port should be modifiable.

Likely a lot of the settings in the overlapping services should be configurable in the same places as chef-server.rb (https://docs.chef.io/config_rb_server_optional_settings.html)

**Comment by juliandunn** [comment]
I'm unclear what the motivation is for this @vinyar -- can you explain why the customer wants to do this?

**Comment by vinyar** [comment]
It's been about 2 weeks since I looked at the docs page, but it seems like the problem got solved? There seem to be a ton of new settings documenting various knobs available in the config cookbook. Not sure if it covers 100% of the knobs, but I'm ok to close this bug.
