### ISSUE TITLE
Timeline details panel sized wrong in Firefox

### ISSUE THREAD

**Issue by echohack** [chef/chef-analytics#26]
In Firefox the timeline details panel appears to break the borders of the box:

![screen shot 2015-05-06 at 16 05 48](https://cloud.githubusercontent.com/assets/3253989/7505664/285fb4a2-f40a-11e4-89a8-8e009c71956a.png)

Developer capture of the html element and css:

![screen shot 2015-05-06 at 16 10 20](https://cloud.githubusercontent.com/assets/3253989/7505697/7b43f34a-f40a-11e4-82ee-841673c68a1e.png)

Firefox health report:
![screen shot 2015-05-06 at 16 18 33](https://cloud.githubusercontent.com/assets/3253989/7505771/96779198-f40b-11e4-92a6-4d98d729b13e.png)

This appears fine in Safari and Chrome.

**Comment by juliandunn** [comment]
I put this one in our JIRA. Thanks @echohack
