### ISSUE TITLE
View run data from analytics

### ISSUE THREAD

**Issue by echohack** [chef/chef-analytics#28]
Currently when you click the button to take you to manage:

![screen shot 2015-05-08 at 13 39 48](https://cloud.githubusercontent.com/assets/3253989/7545116/f6260af2-f587-11e4-8636-71852dd53ef4.png)

It takes you to the node:

![screen shot 2015-05-08 at 13 40 14](https://cloud.githubusercontent.com/assets/3253989/7545126/06a04942-f588-11e4-8a99-5fe89ffe2162.png)

There should be an easy way to take you to the run as well:

![screen shot 2015-05-08 at 13 42 45](https://cloud.githubusercontent.com/assets/3253989/7545138/2c529712-f588-11e4-895e-edc2d059b1da.png)

Or somehow make this data viewable from analytics.

**Comment by juliandunn** [comment]
Hi @echohack I moved this as a feature request into our internal JIRA. Thanks for the feedback!
