### ISSUE TITLE
Document Analytics System Resource Usage

### ISSUE THREAD

**Issue by sean-horn** [chef/chef-analytics#3]
We have this section http://docs.getchef.com/server/install_analytics.html#prerequisites, where we point back at the minimum for Chef Server of 5GB in /var/opt/opscode.

This is a good start, but not as detailed as customers would prefer.
I think a primary question is going to become "What's the projected growth in an Analytics install's storage usage if I have X amount of Chef Server actions occurring?"

At version 1.0.3 of opscode-analytics, it appears that the above is fairly accurate.
Upcoming versions of Analytics are scheduled to become quite a bit more sophisticated, and customer would appreciate documentation about the system resources needed to support that, including but not limited to storage.

**Comment by metadave** [comment]
https://chef.leankit.com/Boards/View/87391175/162558803

**Comment by pburkholder** [comment]
+1, if that's not already obvious via #27  -- thanks, Peter

**Comment by juliandunn** [comment]
This is being worked in the current iteration Peter -- it's in JIRA so I'm closing this out.
