### ISSUE TITLE
Notifications: SMTP credentials not saved

### ISSUE THREAD

**Issue by alexpop** [chef/chef-analytics#30]
I'm running Chef server 12.0.5 and Analytics 1.1.3

I'm creating a new SMTP notification, leaving the Username and Password fields blank. I save and then go back to it and see the two fields filled, username being set to my Chef server user.

Also, I set the username to something else and save. When I go back, it's still on the old value.
Other times, the username shows as saved, but if I logout and then login again, the username is back to the old value.

The other notification fields(to, from, subject, etc) don't have this problem.

**Comment by sersut** [comment]
@alexpop looks like I can not repro this issue. Can we zoom sometime when you are around to look into your system and see what is going wrong?

**Comment by alexpop** [comment]
Sure @sersut, ping me when you are online.

**Comment by juliandunn** [comment]
@alexpop we are going to move Chef-employee reported issues to our jira so if I can get you to open an issue in there if you are still having a problem after triaging, that would be great.
