### ISSUE TITLE
Notification messages are escaped and quoted in email and HTTP

### ISSUE THREAD

**Issue by NickFitz** [chef/chef-analytics#31]
When trying to send a multline message via the `notify()` function via either email or HTTP (webhook), line breaks are escaped. So are backslashes.

For example, the following:

```
rules 'Cookbook Rules'
  rule on action
  when
    parent_type = 'cookbook'
    and
    task = 'update'
  then
    notify('Cookbook Updated', "Cookbook {{ message.parent_name }} was updated.

The update was made by {{ message.requestor_name }}.

They were at address {{ message.remote_hostname }}.

The timestamp is {{ message.recorded_at }}.")
  end
end
```
would be expected to produce the output
```
Cookbook do_culinary_stuff was updated.

The update was made by NickFitz.

They were at address 192.168.1.123.

The timestamp is 2015-05-14T14:12:02Z.
```
but actually produces
```
"Cookbook do_culinary_stuff was updated.\n\nThe update was made by NickFitz.\n\nThey were at address 192.168.1.123.\n\nThe timestamp is 2015-05-14T14:12:02Z."
```
Note the double-quotes around the message, and the substitution of `\n` for the linebreaks that appear in the message template.

If one attempts to include the literal string `\n` within a template, the output is `\\n`, implying that backslashes are also escaped, and thus that generic backslash-escaping of the entire message is being applied before it is sent.

Expected behaviour: I can send email messages or HTTP POSTs that aren't doomed to only ever contain a single line.

**Comment by juliandunn** [comment]
Thanks Nick. I put this one in our backlog in JIRA.
