### ISSUE TITLE
New cookbook creation is not showing up in the UI correctly

### ISSUE THREAD

**Issue by andrewelizondo** [chef/chef-analytics#32]
Creating a new cookbook in chef is currently showing as overwriting a previous cookbook instead of showing up as a new object

![image](https://cloud.githubusercontent.com/assets/6732897/7643919/d1bb3e10-fa52-11e4-8647-00c9e375818d.png)

**Comment by juliandunn** [comment]
I made this into CI-38. https://chefio.atlassian.net/browse/CI-38
