### ISSUE TITLE
Group resource on windows is reporting inconsistent member changes

### ISSUE THREAD

**Issue by andrewelizondo** [chef/chef-analytics#33]
The group resource used on a windows machine appears to be looking at a different id to gather initial state, which makes accurate before/after diffing of changed users challenging.

```
{
  "chef_server_fqdn": "manage-demo.opscode.us",
  "end_time": "2015-04-30T23:29:41Z",
  "id": "8532ef19-4edb-455f-b5ec-34809d6845b3",
  "message_type": "run_converge",
  "message_version": "0.1.0",
  "node_name": "opscode1",
  "organization_name": "opscode",
  "run_id": "d110a65d-6063-4844-976c-9d25bd9e3377",
  "run_list": [
    "recipe[wingroup]"
  ],
  "start_time": "2015-04-30T23:29:39Z",
  "status": "success",
  "total_resource_count": 10,
  "resources": [
    {
      "cookbook_name": "wingroup",
      "cookbook_version": "0.1.3",
      "delta": "",
      "duration": "7",
      "final_state": {
        "members": [
          "Administrator",
          "random"
        ]
      },
      "initial_state": {
        "members": [
          "S-1-5-21-2945668438-2080408112-401244387-500",
          "S-1-5-21-2945668438-2080408112-401244387-1002",
          "S-1-5-21-2945668438-2080408112-401244387-501"
        ]
      },
      "resource_id": "Administrators",
      "resource_name": "Administrators",
      "resource_result": "modify",
      "resource_type": "group"
    }
  ],
  "updated_resource_count": 1
}
```

**Comment by sersut** [comment]
/cc: @juliandunn 

Fixing this is might be challenging. The issue is in Chef Client and it is about how it reports the state in group resource. 

@btm / @jdmundrawala do you guys have an insight of how involved the fix would be?

**Comment by sersut** [comment]
@andrewelizondo also thanks for reporting this. Is there any customer being burned by this? Asking so that we can prioritize it correctly.

**Comment by andrewelizondo** [comment]
@sersut not a large customer impact (e.g not a direct roadblock), however there is one currently impacted that can be communicated out of thread if needed.

**Comment by jdmundrawala** [comment]
I image it's going to be a fairly easy fix. Looks like we just need to do a transformation somewhere

**Comment by juliandunn** [comment]
Yeah I am looking at this and thinking it should be a Chef client bug and prioritized that way. @andrewelizondo can you move it to github.com/chef/chef plz
