### ISSUE TITLE
Permission related actions don't display properly

### ISSUE THREAD

**Issue by jeremiahsnapp** [chef/chef-analytics#34]
When permissions get changed for multiple different objects on the Chef Server all of the related actions displayed in the Analytics web interface show that all of the changed permissions happened only for a single object.

This seems to be caused by insufficient mapping from the `activities.entity_id` to the correct `relationships.entity_id` when the entity type is `Permission`.

Turning on postgresql statement logging revealed the following SQL statement to be the source of the problem since its `LIMIT 1` is arbitrarily grabbing a single record that matches rather than identifying which record from the set of matching records is the correct one.

```
SELECT  "entities".* FROM "entities" INNER JOIN "relationships" ON "entities"."id" = "relationships"."entity_id" WHERE "relationships"."relatable_id" = $1 AND "relationships"."relatable_type" = $2 LIMIT 1
```

This appears to only affect permission related actions since they are the only ones that I know of that require the additional mapping to the `relations` table.

The following screenshot shows what I'm talking about. The reality is I updated the "read" permission of two different roles, a data bag and a "chef-client" cookbook. However, you can clearly see that each action says the "chef-client" cookbook's permission was updated.

![screen shot 2015-05-19 at 3 32 46 pm](https://cloud.githubusercontent.com/assets/430911/7711995/5ff53928-fe3c-11e4-927a-ad090907b036.png)

**Comment by juliandunn** [comment]
I moved this to JIRA as a bug. Thanks Jeremiah
