### ISSUE TITLE
size of rule name editor field is too small

### ISSUE THREAD

**Issue by juliandunn** [chef/chef-analytics#7]
The rule name field is so small as to be unusable. (This is in 1.1.0)

![screen shot 2015-01-21 at 11 18 42 pm](https://cloud.githubusercontent.com/assets/841412/5850472/ee93db60-a1c3-11e4-9b99-81c8c3f89217.png)

**Comment by Shelton** [comment]
Can we ghost in (gray font, same size) "Type Name Here" and give the user the ability to type over their Rule Name in orange? This will give us a 14 character count line that both gives separation between Rules Name > Last Updated and visual space to insert their Rule Name.

Or do we need to input a default rule name?

**Comment by abuecker** [comment]
Fixed.
